[
	{ 'id': 0, 'name': '4th Pz Div HQ', 'side': 1, 'x': 0, 'y': 4, 'unitType': 0, 'equipment': [ { 'id': 0, 'num': 3, 'maxNum': 3 }, { 'id': 3, 'num': 9, 'maxNum': 9 } ], 'fortify': 0, 'customImage': '' }, 
	{ 'id': 1, 'name': '1/II/12 Inf', 'side': 1, 'x': 3, 'y': 8, 'unitType': 1, 'equipment': [ { 'id': 3, 'num': 12, 'maxNum': 12 }, { 'id': 5, 'num': 3, 'maxNum': 3 } ], 'fortify': 0 }, 
	{ 'id': 2, 'name': '2/II/12 Inf', 'side': 1, 'x': 2, 'y': 10, 'unitType': 1, 'equipment': [ { 'id': 3, 'num': 12, 'maxNum': 12 }, { 'id': 5, 'num': 3, 'maxNum': 3 } ], 'fortify': 0 }, 
	{ 'id': 3, 'name': '3/II/12 Inf', 'side': 1, 'x': 3, 'y': 9, 'unitType': 1, 'equipment': [ { 'id': 3, 'num': 12, 'maxNum': 12 }, { 'id': 5, 'num': 3, 'maxNum': 3 } ], 'fortify': 0 }, 
	{ 'id': 4, 'name': '1/I/12 Inf', 'side': 1, 'x': 4, 'y': 1, 'unitType': 1, 'equipment': [ { 'id': 3, 'num': 12, 'maxNum': 12 }, { 'id': 5, 'num': 3, 'maxNum': 3 } ], 'fortify': 0 }, 
	{ 'id': 5, 'name': '2/I/12 Inf', 'side': 1, 'x': 5, 'y': 0, 'unitType': 1, 'equipment': [ { 'id': 3, 'num': 12, 'maxNum': 12 }, { 'id': 5, 'num': 3, 'maxNum': 3 } ], 'fortify': 0 }, 
	{ 'id': 6, 'name': '3/I/12 Inf', 'side': 1, 'x': 4, 'y': 2, 'unitType': 1, 'equipment': [ { 'id': 3, 'num': 12, 'maxNum': 12 }, { 'id': 5, 'num': 3, 'maxNum': 3 } ], 'fortify': 0 }, 
	{ 'id': 7, 'name': 'I/103 Art', 'side': 1, 'x': 0, 'y': 5, 'unitType': 3, 'equipment': [ { 'id': 3, 'num': 3, 'maxNum': 3 }, { 'id': 7, 'num': 12, 'maxNum': 12 } ], 'fortify': 0 }, 
	{ 'id': 8, 'name': 'II/103 Art', 'side': 1, 'x': 0, 'y': 6, 'unitType': 3, 'equipment': [ { 'id': 3, 'num': 3, 'maxNum': 3 }, { 'id': 7, 'num': 12, 'maxNum': 12 } ], 'fortify': 0 }, 
	{ 'id': 9, 'name': '1/I/35 Pz', 'side': 1, 'x': 2, 'y': 9, 'unitType': 5, 'equipment': [ { 'id': 9, 'num': 17, 'maxNum': 17 }, { 'id': 10, 'num': 5, 'maxNum': 5 } ], 'fortify': 0 }, 
	{ 'id': 10, 'name': '2/I/35 Pz', 'side': 1, 'x': 1, 'y': 9, 'unitType': 5, 'equipment': [ { 'id': 9, 'num': 17, 'maxNum': 17 }, { 'id': 10, 'num': 5, 'maxNum': 5 } ], 'fortify': 0 }, 
	{ 'id': 11, 'name': '3/I/35 Pz', 'side': 1, 'x': 0, 'y': 9, 'unitType': 5, 'equipment': [ { 'id': 9, 'num': 5, 'maxNum': 5 }, { 'id': 10, 'num': 17, 'maxNum': 17 }, { 'id': 12, 'num': 3, 'maxNum': 3 } ], 'fortify': 0 }, 
	{ 'id': 12, 'name': '1/II/35 Pz', 'side': 1, 'x': 2, 'y': 8, 'unitType': 5, 'equipment': [ { 'id': 9, 'num': 17, 'maxNum': 17 }, { 'id': 10, 'num': 5, 'maxNum': 5 } ], 'fortify': 0 }, 
	{ 'id': 13, 'name': '2/II/35 Pz', 'side': 1, 'x': 1, 'y': 8, 'unitType': 5, 'equipment': [ { 'id': 9, 'num': 17, 'maxNum': 17 }, { 'id': 10, 'num': 5, 'maxNum': 5 } ], 'fortify': 0 }, 
	{ 'id': 14, 'name': '3/II/35 Pz', 'side': 1, 'x': 0, 'y': 8, 'unitType': 5, 'equipment': [ { 'id': 9, 'num': 5, 'maxNum': 5 }, { 'id': 10, 'num': 17, 'maxNum': 17 }, { 'id': 12, 'num': 3, 'maxNum': 3 } ], 'fortify': 0 }, 
	{ 'id': 15, 'name': '1/I/36 Pz', 'side': 1, 'x': 3, 'y': 1, 'unitType': 5, 'equipment': [ { 'id': 9, 'num': 17, 'maxNum': 17 }, { 'id': 10, 'num': 5, 'maxNum': 5 } ], 'fortify': 0 }, 
	{ 'id': 16, 'name': '2/I/36 Pz', 'side': 1, 'x': 2, 'y': 1, 'unitType': 5, 'equipment': [ { 'id': 9, 'num': 17, 'maxNum': 17 }, { 'id': 10, 'num': 5, 'maxNum': 5 } ], 'fortify': 0 }, 
	{ 'id': 17, 'name': '3/I/36 Pz', 'side': 1, 'x': 1, 'y': 1, 'unitType': 5, 'equipment': [ { 'id': 9, 'num': 5, 'maxNum': 5 }, { 'id': 10, 'num': 17, 'maxNum': 17 }, { 'id': 12, 'num': 3, 'maxNum': 3 } ], 'fortify': 0 }, 
	{ 'id': 18, 'name': '1/II/36 Pz', 'side': 1, 'x': 4, 'y': 4, 'unitType': 5, 'equipment': [ { 'id': 9, 'num': 17, 'maxNum': 17 }, { 'id': 10, 'num': 5, 'maxNum': 5 } ], 'fortify': 0 }, 
	{ 'id': 19, 'name': '2/II/36 Pz', 'side': 1, 'x': 5, 'y': 3, 'unitType': 5, 'equipment': [ { 'id': 9, 'num': 17, 'maxNum': 17 }, { 'id': 10, 'num': 5, 'maxNum': 5 } ], 'fortify': 0 }, 
	{ 'id': 20, 'name': '3/II/36 Pz', 'side': 1, 'x': 4, 'y': 3, 'unitType': 5, 'equipment': [ { 'id': 9, 'num': 5, 'maxNum': 5 }, { 'id': 10, 'num': 17, 'maxNum': 17 }, { 'id': 12, 'num': 3, 'maxNum': 3 } ], 'fortify': 0 }, 	
	{ 'id': 21, 'name': '7th Recon', 'side': 1, 'x': 4, 'y': 5, 'unitType': 6, 'equipment': [ { 'id': 13, 'num': 18, 'maxNum': 18 } ], 'fortify': 0 }, 	
	{ 'id': 22, 'name': 'Wo³yñska Cav HQ', 'side': 2, 'x': 13, 'y': 5, 'unitType': 0, 'equipment': [ { 'id': 0, 'num': 3, 'maxNum': 3 }, { 'id': 6, 'num': 9, 'maxNum': 9 } ], 'fortify': 1, 'customImage': '' }, 
	{ 'id': 23, 'name': '7th Div Cav', 'side': 2, 'x': 4, 'y': 9, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 18, 'maxNum': 18 } ], 'fortify': 1 }, 
	{ 'id': 24, 'name': '1/19 Cav', 'side': 2, 'x': 8, 'y': 4, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 25, 'name': '2/19 Cav', 'side': 2, 'x': 8, 'y': 5, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 26, 'name': '3/19 Cav', 'side': 2, 'x': 9, 'y': 0, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 27, 'name': '4/19 Cav', 'side': 2, 'x': 9, 'y': 2, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 28, 'name': '1/21 Cav', 'side': 2, 'x': 5, 'y': 4, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 29, 'name': '2/21 Cav', 'side': 2, 'x': 7, 'y': 5, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 30, 'name': '3/21 Cav', 'side': 2, 'x': 7, 'y': 6, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 31, 'name': '4/21 Cav', 'side': 2, 'x': 6, 'y': 6, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 32, 'name': '1/12 Cav', 'side': 2, 'x': 12, 'y': 4, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 33, 'name': '2/12 Cav', 'side': 2, 'x': 11, 'y': 4, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 34, 'name': '3/12 Cav', 'side': 2, 'x': 12, 'y': 3, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 35, 'name': '4/12 Cav', 'side': 2, 'x': 11, 'y': 3, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 36, 'name': '1/2sk Cav', 'side': 2, 'x': 11, 'y': 6, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 37, 'name': '2/2sk Cav', 'side': 2, 'x': 12, 'y': 6, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 38, 'name': '3/2sk Cav', 'side': 2, 'x': 11, 'y': 7, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 39, 'name': '4/2sk Cav', 'side': 2, 'x': 12, 'y': 7, 'unitType': 2, 'equipment': [ { 'id': 6, 'num': 9, 'maxNum': 9 }, { 'id': 5, 'num': 1, 'maxNum': 1 } ], 'fortify': 1 }, 
	{ 'id': 40, 'name': '1/4/84 Inf', 'side': 2, 'x': 7, 'y': 8, 'unitType': 1, 'equipment': [ { 'id': 3, 'num': 22, 'maxNum': 22 }, { 'id': 5, 'num': 3, 'maxNum': 3 } ], 'fortify': 1 }, 
	{ 'id': 41, 'name': '2/4/84 Inf', 'side': 2, 'x': 6, 'y': 9, 'unitType': 1, 'equipment': [ { 'id': 3, 'num': 22, 'maxNum': 22 }, { 'id': 5, 'num': 3, 'maxNum': 3 } ], 'fortify': 1 }, 
	{ 'id': 42, 'name': '3/4/84 Inf', 'side': 2, 'x': 6, 'y': 10, 'unitType': 1, 'equipment': [ { 'id': 3, 'num': 22, 'maxNum': 22 }, { 'id': 5, 'num': 3, 'maxNum': 3 } ], 'fortify': 1 }, 
	{ 'id': 43, 'name': '1/11 Inf', 'side': 2, 'x': 7, 'y': 12, 'unitType': 1, 'equipment': [ { 'id': 3, 'num': 22, 'maxNum': 22 }, { 'id': 5, 'num': 3, 'maxNum': 3 } ], 'fortify': 1 }, 
	{ 'id': 44, 'name': '2/11 Inf', 'side': 2, 'x': 11, 'y': 13, 'unitType': 1, 'equipment': [ { 'id': 3, 'num': 22, 'maxNum': 22 }, { 'id': 5, 'num': 3, 'maxNum': 3 } ], 'fortify': 1 }, 
	{ 'id': 45, 'name': '3/11 Inf', 'side': 2, 'x': 14, 'y': 12, 'unitType': 1, 'equipment': [ { 'id': 3, 'num': 22, 'maxNum': 22 }, { 'id': 5, 'num': 3, 'maxNum': 3 } ], 'fortify': 1 },
	{ 'id': 46, 'name': '19 AT', 'side': 2, 'x': 7, 'y': 7, 'unitType': 7, 'equipment': [ { 'id': 8, 'num': 4, 'maxNum': 4 } ], 'fortify': 1 }, 
	{ 'id': 47, 'name': '21 AT', 'side': 2, 'x': 8, 'y': 3, 'unitType': 7, 'equipment': [ { 'id': 8, 'num': 4, 'maxNum': 4 } ], 'fortify': 1 }, 
	{ 'id': 48, 'name': '12 AT', 'side': 2, 'x': 13, 'y': 3, 'unitType': 7, 'equipment': [ { 'id': 8, 'num': 4, 'maxNum': 4 } ], 'fortify': 1 }, 
	{ 'id': 49, 'name': '2sk AT', 'side': 2, 'x': 13, 'y': 7, 'unitType': 7, 'equipment': [ { 'id': 8, 'num': 4, 'maxNum': 4 } ], 'fortify': 1 },
	{ 'id': 50, 'name': '1/2 dak', 'side': 2, 'x': 8, 'y': 7, 'unitType': 4, 'equipment': [ { 'id': 3, 'num': 1, 'maxNum': 1 }, { 'id': 7, 'num': 4, 'maxNum': 4 } ], 'fortify': 1 }, 
	{ 'id': 51, 'name': '2/2 dak', 'side': 2, 'x': 8, 'y': 8, 'unitType': 4, 'equipment': [ { 'id': 3, 'num': 1, 'maxNum': 1 }, { 'id': 7, 'num': 4, 'maxNum': 4 } ], 'fortify': 1 }, 
	{ 'id': 52, 'name': '3/2 dak', 'side': 2, 'x': 8, 'y': 9, 'unitType': 4, 'equipment': [ { 'id': 3, 'num': 1, 'maxNum': 1 }, { 'id': 7, 'num': 4, 'maxNum': 4 } ], 'fortify': 1 }, 
	{ 'id': 53, 'name': '4/2 dak', 'side': 2, 'x': 15, 'y': 9, 'unitType': 4, 'equipment': [ { 'id': 3, 'num': 1, 'maxNum': 1 }, { 'id': 7, 'num': 4, 'maxNum': 4 } ], 'fortify': 1 }, 
	{ 'id': 54, 'name': '8 sap', 'side': 2, 'x': 14, 'y': 5, 'unitType': 1, 'equipment': [ { 'id': 4, 'num': 12, 'maxNum': 12 } ], 'fortify': 1 }, 
	{ 'id': 55, 'name': '1/21 Panc', 'side': 2, 'x': 13, 'y': 6, 'unitType': 5, 'equipment': [ { 'id': 14, 'num': 13, 'maxNum': 13 }], 'fortify': 1 }, 
	{ 'id': 56, 'name': '2/21 Panc', 'side': 2, 'x': 14, 'y': 6, 'unitType': 6, 'equipment': [ { 'id': 15, 'num': 13, 'maxNum': 13 }], 'fortify': 1 }, 
	
];